#!/usr/bin/env bash

ProgName=$(basename $0)
  
sub_help(){
    echo "Usage: $ProgName <subcommand> [options]"
    echo "Subcommands:"
    echo "    init          Create a function file in the current directory"
    echo "    build         Build a docker container using the debug function image"
    echo "    build-proj    Build container assuming functions.rs in src"
    echo "    build-test    Build container assuming functions.rs in src"
    echo "    release       Build a docker container using the release function image"
    echo "    gen           Generate a release Dockerfile for an external build pipeline"
    echo "    fmt           Run rustfmt against functions.rs to make it pretty"
    echo ""
}

sub_init(){
    echo -e ${function_template} > functions.rs
}

sub_fmt() {
    rustfmt --edition=2018 functions.rs
}

sub_build-test() {
    declare imagetag=$1
    
    if [ "${imagetag}" == "" ]; then
        echo "No image tag provided."
        namespace=$(cut -d " " -f3 <<< $(docker info | grep Username))
        imagename=${PWD##*/}
        imagetag=docker.io/$namespace/dev-$imagename:latest
        echo "Going to use: $imagetag"
    fi
    cd src
    echo -e ${docker_debug_build} | docker build -t ${imagetag} -f- .
    cd ..
    docker run -p 8080:8080 $imagetag &
    cargo test
    docker kill $(docker ps | grep number9/dev-full:latest | cut -d' ' -f1)
}

sub_build-proj() {
    declare imagetag=$1
    
    if [ "${imagetag}" == "" ]; then
        echo "No image tag provided."
        namespace=$(cut -d " " -f3 <<< $(docker info | grep Username))
        imagename=${PWD##*/}
        imagetag=docker.io/$namespace/dev-$imagename:latest
        echo "Going to use: $imagetag"
    fi
    cd src
    echo -e ${docker_debug_build} | docker build -t ${imagetag} -f- .
    cd ..
}

sub_build(){
    declare imagetag=$1
    
    if [ "${imagetag}" == "" ]; then
        echo "No image tag provided."
        namespace=$(cut -d " " -f3 <<< $(docker info | grep Username))
        imagename=${PWD##*/}
        imagetag=docker.io/$namespace/dev-$imagename:latest
        echo "Going to use: $imagetag"
    fi
    
    echo -e ${docker_debug_build} | docker build -t ${imagetag} -f- .
}

sub_release(){
    declare imagetag=$1
    
    if [ "${imagetag}" == "" ]; then
        echo "No image tag provided."
        namespace=$(cut -d " " -f3 <<< $(docker info | grep Username))
        imagename=${PWD##*/}
        imagetag=docker.io/$namespace/$imagename:latest
        echo "Going to use: $imagetag"
    fi
    
    echo -e ${docker_build} | docker build -t ${imagetag} -f- .
}

sub_gen(){
    echo -e ${docker_build} > Dockerfile
}

declare -r function_template=$(cat <<-EOM
    pub fn handler() -> tide::Server<()> {\n    
        let mut api = tide::new();\n
        api.at("/").get(|_| async { Ok("Hello, world!") });\n
        api\n
    }\n
EOM
)

declare -r docker_build=$(cat <<-EOM
FROM number9/roche-baseimage as builder\n\n
COPY functions.rs /app-build/src/app/\n\n
RUN cargo build --release\n\n
FROM alpine\n\n
RUN apk add --no-cache libgcc\n\n
RUN addgroup -S rocheuser && adduser -S rocheuser -G rocheuser\n\n
WORKDIR "/app"\n\n
COPY --from=builder --chown=rocheuser /app-build/run.sh /app-build/Cargo.toml /app-build/target/release/roche-service ./\n\n
USER rocheuser\n\n
ENV PORT 8080\n\n
EXPOSE 8080\n\n
CMD ["./run.sh"]\n\n
EOM
)
declare -r docker_debug_build=$(cat <<-EOM
FROM number9/roche-baseimage-debug as builder\n\n
COPY functions.rs /app-build/src/app/\n\n
RUN cargo build\n\n
FROM alpine\n\n
RUN apk add --no-cache libgcc\n\n
RUN addgroup -S rocheuser && adduser -S rocheuser -G rocheuser\n\n
WORKDIR "/app"\n\n
COPY --from=builder --chown=rocheuser /app-build/run.sh /app-build/Cargo.toml /app-build/target/debug/roche-service ./\n\n
USER rocheuser\n\n
ENV PORT 8080\n\n
EXPOSE 8080\n\n
CMD ["./run.sh"]\n\n
EOM
)

declare -r subcommand=$1
case $subcommand in
    "" | "-h" | "--help")
        sub_help
        ;;
    *)
        shift
        sub_${subcommand} $@
        if [ $? = 127 ]; then
            echo "Error: '$subcommand' is not a known subcommand." >&2
            echo "       Run '$ProgName --help' for a list of known subcommands." >&2
            exit 1
        fi
        ;;
esac